version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongo
    environment:
      - DATABASE_URL=sqlite:///db.sqlite3
      - MONGODB_NAME=mantis_shrimp_bot_db
      - MONGODB_HOST=mongodb://mongo:27017/
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,web
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  worker:
    build: .
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
    environment:
      - DATABASE_URL=sqlite:///db.sqlite3
      - MONGODB_NAME=mantis_shrimp_bot_db
      - MONGODB_HOST=mongodb://mongo:27017/
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  beat:
    build: .
    command: celery -A config beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
    environment:
      - DATABASE_URL=sqlite:///db.sqlite3
      - MONGODB_NAME=mantis_shrimp_bot_db
      - MONGODB_HOST=mongodb://mongo:27017/
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  mongo:
    image: mongo:7
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo_data:
